import { PlatFormTypes, CharacterOptions, EpisodesInformation } from "../../typings/exports";
export default function getCompleteInformation(name: string): Promise<{
    title: string;
    description: string;
    image: string;
    score: string;
    ranked: string | null;
    popularityRanking: string | null;
    totalMembers: string | null;
    trailer: string;
    broadcast: string;
    type: string;
    japaneseTitle: string;
    totalEpisodes: string;
    durationPerEpisode: string;
    currentStatus: string;
    genres: string;
    source: string;
    rating: string;
    airedOn: string;
    officialSite: string | undefined;
    watchOn: PlatFormTypes[];
    favorites: string;
    pictures: string[];
    producers: string[];
    theme: string;
    demographic: string;
    characters: CharacterOptions[];
    episodes: EpisodesInformation[];
}>;
